---
title: "pilot"
author: "Karissa Barthelson"
date: "2023-06-14"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(
  autodep = TRUE,
  echo = TRUE, 
  warning = FALSE,
  message = FALSE,
  fig.align = "center", 
  fig.retina = 1,
  out.width ="100%", 
  out.height = "100%"
)
```

```{r packages}
library(tidyverse)
library(readxl)
library(here)
library(magrittr)
library(scales)
library(readxl)
library(ggpubr)
library(ggeasy)
library(ggfortify)
library(ggbeeswarm)
library(ggforce)
library(ggrepel)
library(kableExtra)

# stat analysis
library(broom)
library(lme4)
library(performance)
library(car)
library(emmeans)
library(glmmTMB)
library(MASS)

# set the default theme for ggplot as theme_bw
theme_set(theme_classic())
```

```{r}
meta <- read_excel("data/pilot/7 days/06062023 salbutamol pilot fish metadata.xlsx", 
           sheet = "7 days") %>% 
  
  # tidy up colnames
  mutate(fish_id = as.character(fish_id), 
         treatment = factor(treatment, levels = c("untreated", 
                                                  "20 µM Salbutamol", 
                                                  "100 µM Salbutamol")),
         sex = as.factor(sex), 
         start_time = as.factor(`start time`), 
         genotype = factor(genotype, levels = c("het", "hom"))
         
         )
```


# Introduction

This pilot analysis will determine whether treatment with salbutamol (B2-adrenergiv receptor) can rescue changes to behaviour in a zebrafish model of MPS IIIB (naglu homs). 

The family of fish was consisted 

